services:
  frontend:
    image: govard/code_wizards:latest
    container_name: frontend
    pull_policy: always
    restart: always
    ports:
      - '3000:3000'
    env_file:    
      .env

  test:
    image: govard/code_wizards:beta
    container_name: beta
    pull_policy: always
    restart: always
    ports:
      - '3001:3000'
    env_file:    
      .env