name: deploy_front

on:
  push:
    branches:
      - main
      - develop


jobs:
  build_and_push_to_docker_hub:
    name: docker
    runs-on: ubuntu-latest
    steps:
      - name: Set env BRANCH
        run: echo "BRANCH=$(echo $GITHUB_REF | cut -d'/' -f 3)" >> $GITHUB_ENV

      - name: Set env NEED
        run: |
          if [[ $GITHUB_REF == 'refs/heads/main' ]]; then
              echo "TAG=latest" >> "$GITHUB_ENV"
          else
              echo "TAG=beta" >> "$GITHUB_ENV"
          fi
      - name: Check out the repo
        uses: actions/checkout@v4 
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3 
      - name: Login to Docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push to Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: govard/code_wizards:${{ env.TAG }}

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push_to_docker_hub
    steps:
      - name: executing remote ssh commands to deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          script: |
            sudo docker compose up -d
            sudo docker image prune
